/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardItemsRouteImport } from './routes/dashboard/items'
import { Route as DashboardCreateRouteImport } from './routes/dashboard/create'
import { Route as DashboardEditIdRouteImport } from './routes/dashboard/edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardItemsRoute = DashboardItemsRouteImport.update({
  id: '/dashboard/items',
  path: '/dashboard/items',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreateRoute = DashboardCreateRouteImport.update({
  id: '/dashboard/create',
  path: '/dashboard/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEditIdRoute = DashboardEditIdRouteImport.update({
  id: '/dashboard/edit/$id',
  path: '/dashboard/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/items': typeof DashboardItemsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/items': typeof DashboardItemsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/items': typeof DashboardItemsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/create'
    | '/dashboard/items'
    | '/dashboard'
    | '/dashboard/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/create'
    | '/dashboard/items'
    | '/dashboard'
    | '/dashboard/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dashboard/create'
    | '/dashboard/items'
    | '/dashboard/'
    | '/dashboard/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardCreateRoute: typeof DashboardCreateRoute
  DashboardItemsRoute: typeof DashboardItemsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEditIdRoute: typeof DashboardEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/items': {
      id: '/dashboard/items'
      path: '/dashboard/items'
      fullPath: '/dashboard/items'
      preLoaderRoute: typeof DashboardItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/create': {
      id: '/dashboard/create'
      path: '/dashboard/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/edit/$id': {
      id: '/dashboard/edit/$id'
      path: '/dashboard/edit/$id'
      fullPath: '/dashboard/edit/$id'
      preLoaderRoute: typeof DashboardEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardCreateRoute: DashboardCreateRoute,
  DashboardItemsRoute: DashboardItemsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEditIdRoute: DashboardEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
